include:
  - assets

# User config
author: "Jay Menon"
tagline: "Jay's Portfolio"
description: "Roboticist, Maker, M.S. in Robotics and Autonomous Systems at Arizona State University. My work focuses on robot learning for autonomous navigation and object manipulation!"
keywords: "Roboticist, Engineer, Pineapple, Pineapple Pizza"
email: "menonjay85@gmail.com"
resume: "/assets/Resume - Jay Menon.pdf/"
linkedin: "https://www.linkedin.com/in/jay-menon99/"
# twitter: "https://twitter.com/"
github: "https://github.com/menonjay85/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

