include:
  - assets

# User config
author: "Jay Menon"
tagline: "Jay's Portfolio"
description: "Roboticist & Maker culminating M.S. in Robotics and Autonomous Systems at Arizona State University. I am also the Research Fellow for TSMC (Taiwan Semiconductor Manufacturing Company). My work focuses on robot learning for autonomous navigation, object manipulation & control systems especially in bio-inspired robotics!"
keywords: "Roboticist, Engineer, Pineapple, Pineapple Pizza"
email: "menonjay85@gmail.com"
resume: "assets/resume_jay_menon.pdf"
linkedin: "https://www.linkedin.com/in/jay-menon99/"
# twitter: "https://twitter.com/"
github: "https://github.com/menonjay85/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

